---
receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55689
  otlp/metrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690

extensions:
  pprof:
  zpages:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [otlp/data-prepper/traces, otlp/jaeger]
    metrics:
      receivers: [otlp/metrics]
      processors: [batch]
      exporters: [otlp/data-prepper/metrics]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [zipkin]
  telemetry:
    logs:
      level: "debug"
exporters:
  debug:
  otlp/data-prepper/traces:
    endpoint: http://{{ ansible_default_ipv4.address }}:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/data-prepper/metrics:
    endpoint: http://{{ ansible_default_ipv4.address }}:21891
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
      insecure_skip_verify: true
processors:
    batch:
    span:
